import { AUTO_LOGIN_ENABLED, AUTO_LOGIN_ID, AUTO_LOGIN_PASSWORD, CHECK_NOTES_ON_SUBMITTING_ENABLED, REMOVE_LOADING_VIDEO_ENABLED, VIEW_IN_BROWSER_ENABLED } from './configKeys';

export default {
    [AUTO_LOGIN_ENABLED]: false,
    [AUTO_LOGIN_ID]: '',
    [AUTO_LOGIN_PASSWORD]: '',
    [REMOVE_LOADING_VIDEO_ENABLED]: true,
    [VIEW_IN_BROWSER_ENABLED]: false,
    [CHECK_NOTES_ON_SUBMITTING_ENABLED]: true,
} as Record<string, any>;