import { AUTO_LOGIN_ENABLED, AUTO_LOGIN_ID, AUTO_LOGIN_PASSWORD, CHECK_NOTES_ON_SUBMITTING_ENABLED, COURSE_OVERVIEW_ENABLED, COURSE_OVERVIEW_TYPE, DISABLE_RATE_LIMIT_ENABLED, HIDE_NAME_ENABLED, MORE_VISIBLE_REMAINING_TIME_ENABLED, REMOVE_LOADING_VIDEO_ENABLED, SYLLABUS_LINK_FIX_ENABLED, TIMETABLE_ENTRIES, TIMETABLE_SELECTED_TERM, VIEW_IN_BROWSER_ENABLED } from './config-keys';

export default {
    [AUTO_LOGIN_ENABLED]: false,
    [AUTO_LOGIN_ID]: '',
    [AUTO_LOGIN_PASSWORD]: '',
    [REMOVE_LOADING_VIDEO_ENABLED]: true,
    [VIEW_IN_BROWSER_ENABLED]: false,
    [CHECK_NOTES_ON_SUBMITTING_ENABLED]: true,
    [MORE_VISIBLE_REMAINING_TIME_ENABLED]: true,
    [DISABLE_RATE_LIMIT_ENABLED]: true,
    [COURSE_OVERVIEW_ENABLED]: true,
    [COURSE_OVERVIEW_TYPE]: 'card',
    [TIMETABLE_ENTRIES]: [],
    [TIMETABLE_SELECTED_TERM]: null,
    [HIDE_NAME_ENABLED]: false,
    [SYLLABUS_LINK_FIX_ENABLED]: true,
} as Record<string, any>;